version: "2"

services:
  client:
    build: client 
    networks:
      - simple_demo 
    container_name: client

  server:
    build: server
    ports:
      - "8081:8081" 
    networks:
      - simple_demo
    container_name: server

networks:
    simple_demo:
